### ISSUE TITLE
Diagonal paths?

### ISSUE THREAD

**Issue by bliitzkrieg** [CygnusRoboticus/pathfinding#2]
Does this support diagonal paths?

**Comment by CygnusRoboticus** [comment]
Yes, `:intercardinal` grids navigate adjacent and diagonal paths, here's a test demonstrating [here](https://github.com/CygnusRoboticus/pathfinding/blob/bfdb9bb85f28fd193df87bc276a9304a389cc090/test/pathfinding_test.exs#L300).

**Comment by bliitzkrieg** [comment]
Thanks
